### PR TITLE
12.0 fix GitHub event controller

### PR DESCRIPTION
**Pull request by ddufresne**
https://isidor.numigi.net/web#id=15982&action=298&model=project.task&view_type=form&menu_id=200

### CODE REVIEW

**Comment by ddufresne** [comment]
@foutoucour depends on https://github.com/Numigi/odoo-base-addons/pull/43

**Comment by foutoucour** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4551653&bid=15312319)

**Comment by foutoucour** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4551653&bid=15312319)

**Review by foutoucour — APPROVED** [review]

**Comment by ddufresne** [comment]
@foutoucour les test failent une fois sur deux.

Le problème est dans mock_odoo_request:
https://github.com/Numigi/odoo-base-addons/pull/44

**Review by foutoucour — APPROVED** [review]

**Comment by foutoucour** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/odoo-git-addons/odoo-git-addons/pullRequest?prid=4551653&bid=15312319)

**Pull request merged**
